name: Weather update

on: 
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs: 
  update-weather-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://svanboxel.github.io/secret-profile/
        destination: weather.png
        width: 725
        height: 260
    - run: ls
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update weather image
        branch: main
        commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
        commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
        commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: weather.png
     
